name: STAGING Build and Deploy to Cloud Run

on:
  push:
    branches: ["develop"]

env:
  PROJECT_ID: localize-379823
  GAR_LOCATION: europe-west1
  ARTIFACT_REPO: docker
  SERVICE: front-end-staging
  REGION: europe-west1

jobs:
  deploy:
    permissions:
      contents: "read"
      id-token: "write"

    runs-on: ubuntu-latest
    steps:
      - name: Load info about commit
        id: commit
        uses: pr-mpt/actions-commit-hash@v2

      - name: Checkout
        uses: actions/checkout@v2

      - name: Google Auth
        id: auth
        uses: "google-github-actions/auth@v0"
        with:
          token_format: "access_token"
          workload_identity_provider: "${{ secrets.WIF_PROVIDER }}"
          service_account: "${{ secrets.WIF_SERVICE_ACCOUNT }}"

      - name: Docker Auth
        id: docker-auth
        uses: "docker/login-action@v1"
        with:
          username: "oauth2accesstoken"
          password: "${{ steps.auth.outputs.access_token }}"
          registry: "${{ env.GAR_LOCATION }}-docker.pkg.dev"

      - name: Build and Push Container
        run: |-
          docker build -f apps/front-end/Dockerfile -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REPO }}/${{ env.SERVICE }}:${{ steps.commit.outputs.short }}" ./
          docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REPO }}/${{ env.SERVICE }}:${{ steps.commit.outputs.short }}"

      - name: Deploy app
        uses: google-github-actions/deploy-appengine@v0
        with:
          project_id: ${{ env.PROJECT_ID }}
          service: ${{ env.SERVICE }}
          deliverables: apps/front-end/app.yaml
          img_url: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REPO }}/${{ env.SERVICE }}:${{ steps.commit.outputs.short }}
          promote: true

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
